package models

import (
	"os"
)

var (
	KAFKA_TOPIC_RESOURCE_EVENT                      string
	KAFKA_TOPIC_IOT_ENGINE_FACE_EVENT               string
	KAFKA_TOPIC_ACAAS_FACE_PERMISSION_REQUEST_EVENT string

	KAFKA_TOPIC_TO_RESOURCE_ACK_EVENT         string
	KAFKA_TOPIC_TO_ACAAS_PERMISSION_ACK_EVENT string
	KAFKA_TOPIC_TO_IOT_ENGINE_COMMAND_EVENT   string
)

func init() {

	KAFKA_TOPIC_RESOURCE_EVENT = os.Getenv("KAFKA_TOPIC_RESOURCE_EVENT")
	KAFKA_TOPIC_ACAAS_FACE_PERMISSION_REQUEST_EVENT = os.Getenv("KAFKA_TOPIC_ACAAS_FACE_PERMISSION_REQUEST_EVENT")
	KAFKA_TOPIC_IOT_ENGINE_FACE_EVENT = os.Getenv("KAFKA_TOPIC_IOT_ENGINE_FACE_EVENT")

	KAFKA_TOPIC_TO_IOT_ENGINE_COMMAND_EVENT = os.Getenv("KAFKA_TOPIC_TO_IOT_ENGINE_COMMAND_EVENT")
	KAFKA_TOPIC_TO_RESOURCE_ACK_EVENT = os.Getenv("KAFKA_TOPIC_TO_RESOURCE_ACK_EVENT")
	KAFKA_TOPIC_TO_ACAAS_PERMISSION_ACK_EVENT = os.Getenv("KAFKA_TOPIC_TO_ACAAS_PERMISSION_ACK_EVENT")

}
